//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFinancialCrm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.BankProcesses = new HashSet<BankProcesses>();
            this.Banks = new HashSet<Banks>();
            this.Bills = new HashSet<Bills>();
            this.Categories = new HashSet<Categories>();
            this.Spendings = new HashSet<Spendings>();
        }
    
        public int UserId { get; set; }
        public string Username { get; set; }
        public string PasswordHash { get; set; }
        public bool IsAdmin { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual ICollection<BankProcesses> BankProcesses { get; set; }
        public virtual ICollection<Banks> Banks { get; set; }
        public virtual ICollection<Bills> Bills { get; set; }
        public virtual ICollection<Categories> Categories { get; set; }
        public virtual ICollection<Spendings> Spendings { get; set; }
    }
}
